# Generated by Django 5.1.6 on 2025-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, upload_to='capas/%Y/%m/%d'),
        ),
    ]
