# Generated by Django 5.1.6 on 2025-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, upload_to='capas/%d/%m%/%Y'),
        ),
    ]
